### ISSUE TITLE
More accurate convertion

### ISSUE THREAD

**Issue by hirschnico** [KishanBusa8/currency_converter#10]
My problem is when e.g. converting from Euro to Serbian Dinar I get a pretty accurate value but if I want to convert from Serbinar Dinar to Euro which has the multiplier around 0.0085 it gets kinda inaccurate because the result given from the library is always rounded to 2 digits (in this case 0.01).

As solution I would like a more accurate result.

**Comment by KishanBusa8** [comment]
Hey man @hirschnico,
I've fixed your issue by adding withoutRounding boolean.
If you want full amount then you can set this flag to true.

`await CurrencyConverter.convert(
      from: Currency.usd,
      to: myCurrency,
      amount: 1,
      withoutRounding : true,
    )`
