### ISSUE TITLE
String to currency type

### ISSUE THREAD

**Issue by Fahad-beep** [KishanBusa8/currency_converter#11]
I'm working on a banking app for my client in which one of the feature is to convert currency to current bank account currency let's say I have transaction of 'pkr' but account is of 'sar' then I have to convert then save it. 
now I can do this job locally as making a "Map<String, Currency>" type then continue on this task but I want this to be dynamic. By 'dynamic' I mean to save all the possible currencies on my server which would be "Map<String,dynamic>" on my server then fetch this data now let's say i have to convert SAR to PKR the I'll have to simply call "Map["CurrencyToConvert"]" 
Right now on my server in key value pair, the 'value' can be saved as dynamic and if i fetch it it converts into string so please give a method for it so if i put Currency('PKR') it works.
![Screenshot 2024-02-05 102454](https://github.com/KishanBusa8/currency_converter/assets/78661825/7f53aa15-08b0-482e-aeb6-aafa515319e6)
![Screenshot 2024-02-05 103441](https://github.com/KishanBusa8/currency_converter/assets/78661825/ce8a76b8-5ff2-477f-96a7-24656de219ee)
![Screenshot 2024-02-05 103454](https://github.com/KishanBusa8/currency_converter/assets/78661825/e2729767-1d5c-4f41-9900-79ffa84141c6)
![Screenshot 2024-02-05 103645](https://github.com/KishanBusa8/currency_converter/assets/78661825/a2f0add5-a5b7-41e4-b0b9-43cfee3197bd)

**Comment by KishanBusa8** [comment]
Hey man @Fahad-beep 
You can convert your string in to the Currency by below code. Just convert your string in to the Currency and then send it will work.


`Currency.values.byName('pkr');`
