### ISSUE TITLE
Turkish to SAR

### ISSUE THREAD

**Issue by Fahad-beep** [KishanBusa8/currency_converter#12]
its giving an error on converting turkish lira to SAR
![Screenshot 2024-02-05 111947](https://github.com/KishanBusa8/currency_converter/assets/78661825/45bb23f1-d9ea-40fe-a7e4-b58d1db90b0c)
![Screenshot 2024-02-05 111957](https://github.com/KishanBusa8/currency_converter/assets/78661825/a3d519d6-b26d-4ef8-914c-872c62f2ef42)
my app's feature is depending on this so please fix it as soon as possible

**Comment by KishanBusa8** [comment]
Hey @Fahad-beep  man.
Your issue has been fixed by [#16 ]( https://github.com/KishanBusa8/currency_converter/pull/16) this.
Now you can use the latest version of the package which is 2.0.0 for now.?

Thanks.
