### ISSUE TITLE
The Currency Convert API call is not functioning.

### ISSUE THREAD

**Issue by ashiq-mvp** [KishanBusa8/currency_converter#14]
**Describe the bug**
Failed to fetch fawazahmed0/currency-api@1 from GitHub.

The Currency Convert API call is completely non-functional. Additionally, after attempting to convert the currency, it consistently returns 0.0, after catching the error.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/KishanBusa8/currency_converter/assets/133241376/9f8fcbc7-74b3-4e80-8c62-48abafebe38d">

**Comment by ashiq-mvp** [comment]
@KishanBusa8 This issue is urgent and requires immediate attention.

**Comment by KishanBusa8** [comment]
Hey @ashiq-mvp Thanks for the update I am looking in to it

**Comment by faisalkcmvp** [comment]
@KishanBusa8 I fixed on #15

**Comment by KishanBusa8** [comment]
Hey @faisalkcmvp  man.
Thanks for these fixes but this issue has already been fixed by [#16 ]( https://github.com/KishanBusa8/currency_converter/pull/16).
Now you can use the latest version of the package which is 2.0.0 for now.

Thanks.
