### ISSUE TITLE
Invalid Double

### ISSUE THREAD

**Issue by Fahad-beep** [KishanBusa8/currency_converter#17]
**Describe the bug**
For some reason on converting the currency of specific amount it throws an error that "convert err FormatException: Invalid double"
whilst yesterday it was working fine but today its throwing this error. ( I have the latest dependency of currency_converter ^2.0.0 )

**To Reproduce**
1. write currency converter code which is
 "CurrencyConverter.convert(
from: Currency.usd
to: currency.pkr
amount: 100,
);
2. run this code with async and await then it will give you an error 
**Expected behavior**
it was converting before till yesterday

**Screenshots**
![Screenshot 2024-03-15 142021](https://github.com/KishanBusa8/currency_converter/assets/78661825/23031504-e7cd-488c-b415-301e724868a6)
![Screenshot 2024-03-15 142414](https://github.com/KishanBusa8/currency_converter/assets/78661825/33bff6cd-762a-4794-8378-7702abe61ee2)
![Screenshot 2024-03-15 142431](https://github.com/KishanBusa8/currency_converter/assets/78661825/edb83903-63ea-456a-9b38-90de043b3752)

**Smartphone :**
 - Device:  Medium Phone API 33
 - OS: Android
 - Version 13.0 Tiramisu

**Comment by KishanBusa8** [comment]
Hey, Man @Fahad-beep  I've double checked this issue from my side and it's working perfectly fine. There is no error can you please check again.

**Comment by Fahad-beep** [comment]
Yes It's working know. I enabled this feature again to check if it's converting and it is. Thank you
![Screenshot 2024-03-15 165450](https://github.com/KishanBusa8/currency_converter/assets/78661825/e446eba9-a23b-4335-a5e8-031dc85570d5)
